# docker-compose.yml
version: '3.8'
services:
  bgtags:
    image: node:latest
    volumes:
      - type: bind
        source: ./
        target: /app
      - type: volume
        source: nodemodules
        target: /app/node_modules
        volume:
          nocopy: true
    working_dir: /app
    command: npm run dev
    ports: 
      - 3302:3302
    env_file: .env

volumes:
  nodemodules: